// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9Xful2s289gbA26HEy5Y6IqdySpidAQ',
    appId: '1:602160717104:web:32dbcc12ae53007eb87cf5',
    messagingSenderId: '602160717104',
    projectId: 'document-summarizer-733b5',
    authDomain: 'document-summarizer-733b5.firebaseapp.com',
    storageBucket: 'document-summarizer-733b5.appspot.com',
    measurementId: 'G-S437VBLJLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSK-8ika2KSFXKOWVcq_3NXdWX87GbvJA',
    appId: '1:602160717104:android:72b8c9b450972cefb87cf5',
    messagingSenderId: '602160717104',
    projectId: 'document-summarizer-733b5',
    storageBucket: 'document-summarizer-733b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVWdLtcQgk1bt9qtkIo-EladFKKXrtro',
    appId: '1:602160717104:ios:3ca09362c3699efdb87cf5',
    messagingSenderId: '602160717104',
    projectId: 'document-summarizer-733b5',
    storageBucket: 'document-summarizer-733b5.appspot.com',
    iosClientId: '602160717104-mj681ld7ahg64ccl4gk66h1dl6s4h40m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpVWdLtcQgk1bt9qtkIo-EladFKKXrtro',
    appId: '1:602160717104:ios:8f9ecaec30d3dd3db87cf5',
    messagingSenderId: '602160717104',
    projectId: 'document-summarizer-733b5',
    storageBucket: 'document-summarizer-733b5.appspot.com',
    iosClientId: '602160717104-fbm2gn9sp1p6gemscdae6ftthl7bparq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGemini.RunnerTests',
  );
}
